### ISSUE TITLE
Not closing\working while in game

### ISSUE THREAD

**Issue by Lachfish** [Wulf2k/MedievalDynasty-CheatMenu-DLL#1]
Hello, 
I have installed the xinput1_3.dll, in the correct location for steam. When I run Medieval Dynasty, It opens, but then the cheat menu doesnt show up as an option. However, it loads open on a separate tab, both under the 'Medieval Dynasty' window icon.

**Comment by Wulf2k** [comment]
The 1.5+ update for Medieval Dynasty removed files from the game's archive file that were necessary for the Cheat Menu to function.

I should be releasing instructions on how to work around this to YouTube in the next couple of days (and I'll update here) but, unfortunately, more steps are now required after installing this DLL.

**Comment by Lachfish** [comment]
Alright. Thanks for reaching out!

**Comment by Wulf2k** [comment]
It's not as smooth a procedure as I'd like, but here's a video showing how to get it working in 1.5

https://www.youtube.com/watch?v=06n0JKxKDGk
